# Generated by Django 4.0.2 on 2022-02-13 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitteruser',
            name='twitter_oauth_token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitter_users.twitterauthtoken'),
        ),
    ]
