# Generated by Django 4.0.2 on 2022-02-23 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_users', '0002_twitterdmauthtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitteruser',
            name='twitter_dm_oauth_token',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='twitter_users.twitterdmauthtoken'),
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='twitter_oauth_token',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='twitter_users.twitterauthtoken'),
        ),
    ]
