# Generated by Django 4.0.2 on 2022-02-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_users', '0002_alter_twitteruser_twitter_oauth_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitteruser',
            name='minutes_rt',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
