# Generated by Django 4.0.2 on 2022-02-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_users', '0003_twitteruser_twitter_dm_oauth_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitteruser',
            name='last_tweet_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
