# Generated by Django 4.0.2 on 2022-02-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_users', '0004_twitteruser_last_tweet_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitteruser',
            name='last_tweet_id',
        ),
        migrations.AddField(
            model_name='twitteruser',
            name='last_rm_rt_check',
            field=models.DateTimeField(null=True),
        ),
    ]
